"""
controller_replay.py - replay a real recording through the controller and count chatter.

WHY THIS EXISTS

docs/finding_ladder_hysteresis.md reported that the recommended estimator retuning
produces 459 prompt changes with 168 arriving faster than a crossfade, against 36 and 0
at the deployed settings. Those numbers decided what the next hardware session does.
They were produced by code that was never committed, which puts them outside the rule in
HANDOFF section 9: every number in the manuscript is regenerated by a script rather than
remembered.

Rebuilding the replay here disagreed with all of them - the true counts are 382 / 136 and
28 / 0 - and it also showed that ladder_margin, which that document recommended enabling,
latched the controller and stopped the music responding at all. Uncommitted measurements
are not measurements.

This is that script. It reconstructs z from a raw recording under an arbitrary estimator
configuration, drives the REAL controller with it, and measures what a participant would
have heard:

    changes            how many times the prompt actually changed
    median gap         typical seconds between changes
    under a crossfade  changes arriving faster than the crossfade can resolve

The third column is the one that matters. A switch inside a crossfade is not a musical
transition, it is a click - that is the defect that made PILOT01's audio unusable.

WHAT IT REFUSES TO DO

It does not reimplement the feature extractor (trap 4). It calls FeatureExtractor, and it
refuses to report anything if its reconstruction correlates below r = 0.9 with the
log(beta/alpha) the session actually logged - the same gate estimator_sweep.py applies. A
hand-rolled Welch correlates r = 0.05 with the logged output, so this check is the
difference between measuring this pipeline and measuring a different one that resembles
it.

It does not assume the session clock and the raw sample clock share an origin (trap 3).
The offset is found by correlation and reported.

It refuses sessions with no baseline SD, because build_prompt's thresholds are in z units
and raw log units are ~8x smaller (trap 5).

USAGE

    python scripts/controller_replay.py                       # deployed vs retuned
    python scripts/controller_replay.py --sweep               # margin x dwell grid
    python scripts/controller_replay.py --window 2 --hop 0.5 --tau 0.5 --margin 0.5
"""

from __future__ import annotations

import argparse
import glob
import os
import sys

import numpy as np

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, "src"))

from eeg_features import FeatureConfig, FeatureExtractor  # noqa: E402
from music_engine import PromptGovernor, state_rung  # noqa: E402
from session_logger import load_raw, load_session  # noqa: E402

FS = 256.0
_TREND_WINDOW_HOPS = 20          # must match live_music._TREND_WINDOW_HOPS

DEPLOYED = (4.0, 1.0, 3.0)
RETUNED = (2.0, 0.5, 0.5)

# LSL timestamps jitter by a few ms, so a gap of exactly one hop can measure 0.9895 s
# against a 1 s crossfade. Counting that as "faster than the crossfade" would report the
# deployed configuration's own hop floor as chatter - 3 phantom clicks on PILOT01. A
# change cannot arrive sooner than one hop by construction, so the tolerance absorbs
# jitter without hiding anything: at the retuned 0.5 s hop the distinction is 0.5 s
# against 1.0 s and nowhere near this band.
_JITTER_S = 0.05


# ------------------------------------------------------------------ estimator


def reconstruct(chans, ts, pair, window_s, hop_s, tau_s):
    """
    (raw time, smoothed log(beta/alpha)) through the deployed feature path.

    The extractor is CALLED, never reimplemented. Timestamps are the window END, which
    is where the control loop would have had the value; any constant disagreement with
    the session clock is absorbed by the offset search in align().

    TIME COMES FROM THE LSL TIMESTAMPS, NOT THE SAMPLE INDEX. PILOT01's raw stream has
    two dropouts, the worst 10.67 s long. Across a gap, sample_index / fs and real time
    diverge permanently, so no constant offset can align them and the fidelity check
    caps out around r = 0.66. This is trap 3 in a second costume: the two clocks differ
    by more than an origin.
    """
    cfg = FeatureConfig(sampling_rate=FS, window_seconds=window_s, hop_seconds=hop_s,
                        frontal_channels=pair)
    ex = FeatureExtractor(cfg)
    nw, nh = cfg.window_samples, cfg.hop_samples
    t, v = [], []
    for s0 in range(0, chans.shape[1] - nw + 1, nh):
        f = ex.extract(chans[:, s0:s0 + nw])
        if f.valid and np.isfinite(f.log_beta_alpha):
            t.append(float(ts[s0 + nw - 1]))
            v.append(f.log_beta_alpha)
    if len(v) < 10:
        return np.array([]), np.array([])
    v = np.asarray(v, dtype=float)
    a = 1.0 - np.exp(-hop_s / tau_s)
    out = np.empty_like(v)
    acc = v[0]
    for i, x in enumerate(v):
        acc += a * (x - acc)
        out[i] = acc
    return np.asarray(t, dtype=float), out


def align(t, v, session):
    """
    Offset between the session clock and the raw sample clock, and the fidelity r.

    Both come out of the same correlation scan, which is the point: the offset is only
    trustworthy if the series being correlated is a faithful reproduction, and r says
    whether it is. Trap 3 - the offset is +6.25 s on the alphatest and +16 s on PILOT01,
    where the raw file starts well after the session clock does. Never assume zero, and
    do not let the search range decide the answer: an offset landing exactly on a search
    bound means the range was too narrow, not that the offset is that value.

    `v` must be UNSMOOTHED. The session logs feats.log_beta_alpha, which is the raw
    per-window value; smoothed_log_beta_alpha is a separate field. Correlating a smoothed
    reconstruction against the unsmoothed log costs about 0.3 of r and drags the offset
    with it.
    """
    w = [q for q in session["windows"]
         if q.get("phase") == "intervention"
         and isinstance(q.get("log_beta_alpha"), (int, float))
         and np.isfinite(q["log_beta_alpha"])]
    if len(w) < 50 or not t.size:
        return 0.0, float("nan")
    wt = np.asarray([q["elapsed_s"] for q in w], dtype=float)
    wv = np.asarray([q["log_beta_alpha"] for q in w], dtype=float)
    best = (0.0, -9.0)
    for off in np.arange(-60.0, 60.01, 0.25):
        mine = np.interp(wt - off, t, v, left=np.nan, right=np.nan)
        ok = np.isfinite(mine)
        if ok.sum() < 50:
            continue
        r = float(np.corrcoef(mine[ok], wv[ok])[0, 1])
        if r > best[1]:
            best = (float(off), r)
    return best


# ----------------------------------------------------------------- the replay


def replay(z, t, target_z, margin, dwell, crossfade_s):
    """
    Drive the real controller with a z series and record what would have been heard.

    `t` is real elapsed seconds, so a dropout shows up as one long gap rather than as
    silently compressed time - which matters, because the whole measurement is a rate.
    """
    gov = PromptGovernor(target_z=target_z, ladder_margin=margin,
                         min_dwell_seconds=dwell)
    change_times, prompts = [], []
    prev = None
    for i, value in enumerate(z):
        now = float(t[i])
        p = gov.update(float(value), now=now)
        if prev is not None and p != prev:
            change_times.append(now)
            prompts.append(p)
        prev = p
    gaps = np.diff(np.asarray(change_times)) if len(change_times) > 1 else np.array([])
    return {
        "changes": len(change_times),
        "median_gap": float(np.median(gaps)) if gaps.size else float("nan"),
        "under_crossfade": (int((gaps < crossfade_s - _JITTER_S).sum())
                            if gaps.size else 0),
        "distinct": len(set(prompts)),
        "suppressed": gov.suppressed,
    }


def logged_z(session):
    """
    The z the session itself recorded, with its own timestamps.

    This is the calibration path. It is exact - no reconstruction, no clock alignment -
    but it exists only for the estimator the session was actually recorded with, so it
    cannot answer anything about a retuned one. Replaying it and comparing against the
    reconstruction is what puts a number on the reconstruction's error, instead of
    leaving it as an unquantified worry. scripts/verify_claims.py uses this path.
    """
    w = [q for q in session["windows"]
         if q.get("phase") == "intervention"
         and isinstance(q.get("z"), (int, float)) and np.isfinite(q["z"])]
    return (np.asarray([q["z"] for q in w], dtype=float),
            np.asarray([q["elapsed_s"] for q in w], dtype=float))


def rung_flips(z, margin):
    """Rung transitions, before build_prompt's mapping absorbs any of them."""
    prev, n = None, 0
    for value in z:
        r = state_rung(float(value), previous_rung=prev, margin=margin)
        if prev is not None and r != prev:
            n += 1
        prev = r
    return n


# ------------------------------------------------------------------- plumbing


def load(session_dir):
    session = load_session(session_dir)
    raw = load_raw(session_dir)
    chans = raw[:, 1:].T.astype(float)
    ts = raw[:, 0].astype(float)
    # Samples and their timestamps are dropped together, so the time axis survives.
    ok = np.isfinite(chans).all(axis=0) & np.isfinite(ts)
    chans, ts = chans[:, ok], ts[ok]
    ts = ts - ts[0]
    # Read the pair off the data, never off memory - this is how trap 2 surfaced.
    pair = tuple(session["manifest"].get("index_channels") or ("AF7", "AF8"))
    base = (session.get("baseline") or [{}])[0]
    return session, chans, ts, pair, base


def z_series(chans, ts, pair, session, base, window_s, hop_s, tau_s, offset):
    """z over the intervention phase only, in the units build_prompt expects (trap 5)."""
    t, v = reconstruct(chans, ts, pair, window_s, hop_s, tau_s)
    if not v.size:
        return np.array([]), np.array([])
    mean = float(base["baseline_mean_log_beta_alpha"])
    sd = float(base["baseline_sd_log_beta_alpha"])
    z = (v - mean) / sd
    iv = [q["elapsed_s"] for q in session["windows"] if q.get("phase") == "intervention"]
    if not iv:
        return z, t
    keep = (t >= min(iv) - offset) & (t <= max(iv) - offset)
    return z[keep], t[keep]


def main() -> int:
    p = argparse.ArgumentParser(description="Replay a recording through the controller")
    p.add_argument("--session", default=None)
    p.add_argument("--window", type=float, default=None)
    p.add_argument("--hop", type=float, default=None)
    p.add_argument("--tau", type=float, default=None)
    p.add_argument("--margin", type=float, default=0.0)
    p.add_argument("--dwell", type=float, default=0.0,
                   help="minimum seconds a prompt is held once adopted")
    p.add_argument("--target", type=float, default=-1.0)
    p.add_argument("--crossfade", type=float, default=None)
    p.add_argument("--sweep", action="store_true",
                   help="margin x dwell grid instead of a single setting")
    args = p.parse_args()

    d = args.session
    if d is None:
        cands = sorted(glob.glob(os.path.join(_ROOT, "sessions", "PILOT*")))
        d = cands[-1] if cands else None
    if d is None:
        print("No session found; pass --session.")
        return 1

    session, chans, ts, pair, base = load(d)
    if not base.get("baseline_sd_log_beta_alpha"):
        print("  This session has no baseline SD, so z units cannot be recovered (trap 5).")
        print("  Thresholds would be off by the baseline SD, roughly 8x. Refusing.")
        return 1
    crossfade = args.crossfade if args.crossfade is not None else float(
        (session["manifest"].get("engine_config") or {}).get("crossfade_seconds", 1.0))

    print("=" * 78)
    print("CONTROLLER REPLAY - what a participant would actually have heard")
    print("=" * 78)
    print(f"  session   : {os.path.basename(d)}")
    print(f"  channels  : {'/'.join(pair)}   (read from the manifest, not from memory)")
    print(f"  crossfade : {crossfade:g} s")

    # FIDELITY GATE. Reconstruct the DEPLOYED configuration and check it against the
    # session's own log. If this fails, nothing below is measuring this pipeline.
    # tau ~ 0 so the reconstruction is unsmoothed, matching the logged field.
    t0, v0 = reconstruct(chans, ts, pair, DEPLOYED[0], DEPLOYED[1], 0.001)
    offset, r = align(t0, v0, session)
    print(f"  clock offset (session - raw): {offset:+.2f} s     fidelity r = {r:.3f}")
    if not np.isfinite(r) or r < 0.9:
        print()
        print("  !! r < 0.9 - the reconstruction does not reproduce the deployed")
        print("     pipeline, so these counts would describe a different system.")
        return 1
    print()

    # CALIBRATION. Replay the session's OWN logged z at the deployed settings, where the
    # answer is known, and compare against the reconstruction of the same settings. The
    # difference is the reconstruction's error, and it is the error bar on every retuned
    # number below - which cannot be checked this way, because no log exists for them.
    lz, lt = logged_z(session)
    zr, tr_ = z_series(chans, ts, pair, session, base, *DEPLOYED, offset)
    if lz.size > 50 and zr.size > 50:
        a = replay(lz, lt, args.target, 0.0, 0.0, crossfade)
        b = replay(zr, tr_, args.target, 0.0, 0.0, crossfade)
        print(f"  calibration, deployed settings, margin 0, dwell 0:")
        print(f"    from the session log      {a['changes']:>4} changes"
              f"   {a['under_crossfade']} under a crossfade   (exact)")
        print(f"    from the reconstruction   {b['changes']:>4} changes"
              f"   {b['under_crossfade']} under a crossfade")
        if a["changes"]:
            print(f"    reconstruction error     {abs(b['changes'] - a['changes']) / a['changes']:.0%}"
                  f"  - treat every count below as approximate to about this much")
        print()

    if args.window or args.hop or args.tau:
        win, hop, tau = (args.window or 4.0, args.hop or 1.0, args.tau or 3.0)
        configs = [(f"custom    {win:g} s / {hop:g} s / tau {tau:g}", win, hop, tau)]
    else:
        configs = [("deployed  4 s / 1 s / tau 3", *DEPLOYED),
                   ("retuned   2 s / 0.5 s / tau 0.5", *RETUNED)]

    # The dwell axis stops at 2 s deliberately. A dwell of one crossfade already drives
    # sub-crossfade switches to zero by construction, and anything much larger buys
    # nothing while costing responsiveness one-for-one - the library engine acts within a
    # crossfade, so worst case is dwell + crossfade. An 8 s dwell leaves the retuned
    # estimator slower end-to-end than the deployed one it was meant to beat, which is
    # why the interesting region is small and near the crossfade.
    grid = ([(0.0, 0.0), (0.0, 0.5), (0.0, 1.0), (0.0, 2.0),
             (0.25, 0.0), (0.25, 1.0),
             (0.5, 0.0), (0.5, 1.0)] if args.sweep
            else [(args.margin, args.dwell)])

    for label, win, hop, tau in configs:
        z, tz = z_series(chans, ts, pair, session, base, win, hop, tau, offset)
        if z.size < 50:
            print(f"  {label}: only {z.size} usable values, skipped")
            continue
        print(f"  {label}    n={z.size}   z sd={z.std(ddof=1):.2f}")
        print(f"    {'margin':>7}{'dwell':>7}{'rung flips':>12}{'changes':>9}"
              f"{'median gap':>12}{'< crossfade':>13}")
        print("    " + "-" * 60)
        for margin, dwell in grid:
            m = replay(z, tz, args.target, margin, dwell, crossfade)
            gap = f"{m['median_gap']:.1f} s" if np.isfinite(m["median_gap"]) else "-"
            print(f"    {margin:>7.2f}{dwell:>7.1f}{rung_flips(z, margin):>12}"
                  f"{m['changes']:>9}{gap:>12}{m['under_crossfade']:>13}")
        print()

    print("=" * 78)
    print("  A change arriving inside a crossfade is a click, not a transition.")
    print("  That last column is what disqualifies a configuration.")
    print("=" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
